name: Lint and Format

on:
    push:
        branches: [main]
    pull_request:

jobs:
    website:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: pnpm/action-setup@v6

            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm

            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
            - run: pnpm format:check
    examples:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: '25'
            - run: ./gradlew spotlessCheck
              working-directory: examples
